MenuManager {
 MenuPresets {
  MenuPreset RP_DispatchPopup {
   Layout "{50A6D7B100000001}UI/RP_DispatchHUD.layout"
   ActionContext "DialogContext"
   Class "RP_DispatchPopup"
  }
  MenuPreset RP_AdminPanel {
   Layout "{60B1C0A100000001}UI/RP_AdminPanel.layout"
   ActionContext "DialogContext"
   Class "RP_AdminPanelUI"
  }
 }
}