ActionManager {
 Actions {
  Action RP_OpenDispatch {
   InputSource InputSourceSum "{8C0F3E1200000201}" {
    Sources {
     InputSourceValue "{8C0F3E1200000202}" {
      Input "keyboard:KC_J"
      Filter InputFilterClick "{8C0F3E1200000203}" {
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext CharacterGeneralContext {
   ActionRefs +{
    "RP_OpenDispatch"
   }
  }
  ActionContext CarContext {
   ActionRefs +{
    "RP_OpenDispatch"
   }
  }
  ActionContext TurretContext {
   ActionRefs +{
    "RP_OpenDispatch"
   }
  }
 }
}
