ActionManager {
 Actions {
  Action RP_OpenDispatch {
   InputSource InputSourceSum "{8C0F3E1200000201}" {
    Sources {
     InputSourceValue "{8C0F3E1200000202}" {
      FilterPreset "select"
      Input "keyboard:KC_LBRACKET"
      Filter InputFilterClick "{8C0F3E1200000203}" {
      }
     }
    }
   }
  }
  Action RP_ToggleSurveillance {
   InputSource InputSourceSum "{8C0F3E1200000211}" {
    Sources {
     InputSourceValue "{8C0F3E1200000212}" {
      FilterPreset "select"
      Input "keyboard:KC_RBRACKET"
      Filter InputFilterClick "{8C0F3E1200000213}" {
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext CharacterGeneralContext {
   ActionRefs +{
    "RP_OpenDispatch"
    "RP_ToggleSurveillance"
   }
  }
  ActionContext CarContext {
   ActionRefs +{
    "RP_OpenDispatch"
    "RP_ToggleSurveillance"
   }
  }
  ActionContext TurretContext {
   ActionRefs {
    "RP_OpenDispatch"
    "RP_ToggleSurveillance"
   }
  }
  ActionContext DialogContext {
   ActionRefs +{
    "RP_OpenDispatch"
   }
  }
 }
}