SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{8C0F3E1200000300}" {
   m_sName "CopsNRobbersRP"
   m_sDisplayName "Cops n Robbers RP"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{8C0F3E1200000301}" {
     m_sActionName "RP_OpenDispatch"
     m_sDisplayName "Open Dispatch Popup"
    }
   }
  }
 }
}
