SCR_MissionHeaderCombatOps {
 World "{F5E250CFD54DEC2F}Worlds/TestWorld.ent"
 SystemsConfig "{C50579A2EC48E8EF}Configs/Systems/MissionSystems.conf"
 m_sName "Cops n Robbers"
 m_sAuthor "WackyIraqi"
 m_sDescription "Join the Police Force and keep the streets safe."\
 "Only the Police Force is player controllable at the moment."\
 ""
 m_sDetails "Spawn in, spawn a cop car, and go on patrol."\
 ""\
 "Use \"]\" (right bracket) to turn on the Speed Radar. Use \"[\" (left bracket) to open the dispatch menu."
 m_sIcon "{98377D637BE94A6A}Assets/Screenshots/CopsNRobbers1.edds"
 m_sLoadingScreen "{98377D637BE94A6A}Assets/Screenshots/CopsNRobbers1.edds"
 m_sPreviewImage "{98377D637BE94A6A}Assets/Screenshots/CopsNRobbers1.edds"
 m_sGameMode "Cops n Robbers"
 m_iPlayerCount 32
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_bOverrideScenarioTimeAndWeather 1
 m_bRandomStartingDaytime 1
 m_fDayTimeAcceleration 12
 m_fNightTimeAcceleration 12
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
 m_aTaskTypesAvailable {
  SCR_ScenarioFrameworkTaskType "{6956376F499AB647}" {
   m_eTypeOfTask DELIVER
  }
  SCR_ScenarioFrameworkTaskType "{6956376F499AB660}" {
   m_eTypeOfTask DESTROY
  }
  SCR_ScenarioFrameworkTaskType "{6956376F499AB667}" {
   m_eTypeOfTask CLEAR_AREA
  }
  SCR_ScenarioFrameworkTaskType "{6956376F499A5105}" {
   m_eTypeOfTask KILL
  }
 }
 m_aFactionAliases {
  SCR_ScenarioFrameworkFactionAliasConfig "{6956376F499A5106}" {
   m_sAlias "PLAYERS"
   m_sFactionKey "Police"
  }
 }
}